name: Build and Test Node.js Library

on:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: aarch64
          - os: windows-latest
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Node.js test
        env:
          CRUDJT_AUTOTEST_ALLOWED: true
        working-directory: ./test-neon-package
        run: |
          npm install
          node test.js
