name: Build and Test Node.js Library

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: aarch64
          - os: windows-latest
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      # Крок для отримання коду з репозиторію
      - uses: actions/checkout@v4

      # Налаштування Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Встановлення залежностей
      - name: Install dependencies
        run: |
          npm install
          npm run cargo-build -- --release

      - name: Create symlink for `tests`
        run: |
          if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS" ]]; then
            ln -s "$(pwd)" test-neon-package
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            cmd /C "mklink /D test-neon-package %CD%"
          fi
        shell: bash


      - name: Run Node.js test
        working-directory: ./test-neon-package
        run: node test.js
